### ISSUE TITLE
NATS Jetstream kv Remote Cache

### ISSUE THREAD

**Issue by gedw99** [ariga/entcache#12]
I am looking to change from Redis to NATS KV .

nats kv is a globally distributed fault tolerate kv store that is new and built into nats.

I have been using it instead of redis. So far it’s been awesome 
It’s supports TTL and purging .

It might be interesting to explore it as a “driver” also.

https://nats.io/blog/kv-cli/ has an explanation and demo video.

the nats cli works out of the box with it .
https://github.com/nats-io/natscli

The golang nats client also has it.
https://github.com/nats-io/nats.go

the nats server needs no specific configuration to work with kv. It just works.

https://github.com/nats-io/nats-server

the security model is based on jwt .
https://github.com/nats-io/nsc

I can get something setup to explore integration if there is any interest ??

**Comment by giautm** [comment]
You can write custom Driver that it the AddGetDeleter interface then passing it into Levels().

**Comment by a8m** [comment]
Hey @gedw99 and @giautm and sorry for the delayed response.

Yes, like @giautm mentioned, implementing the [`AddGetDeleter`](https://pkg.go.dev/ariga.io/entcache#AddGetDeleter) should do the job. Please, let me know if you have an experiment in a GitHub repository, and we can add it to our README, or you can contribute it as a separate package under this project. 

Thanks ❤️

**Comment by gedw99** [comment]
thanks @a8m 

I have too many other commitments right now, so if anyone else wants to go for it your welcome.

**Comment by giautm** [comment]
Simple implement for NATS client.
```go
package entcache

import (
	"context"
	"fmt"
	"time"

	"github.com/nats-io/nats.go"
)

// NATS provides an NATS cache that implements the AddGetter interface.
type NATS struct {
	kvStore nats.KeyValue
}

var _ AddGetDeleter = (*NATS)(nil)

// NewDefaultNATS return default NATS cache
func NewDefaultNATS(bucket string) (*NATS, error) {
	conn, err := nats.Connect(nats.DefaultURL)
	if err != nil {
		return nil, err
	}
	js, err := conn.JetStream()
	if err != nil {
		return nil, err
	}

	keyValue, err := js.KeyValue(bucket)
	if err != nil {
		return nil, err
	}

	return NewNATS(keyValue), nil
}

func NewNATS(kvStore nats.KeyValue) *NATS {
	return &NATS{
		kvStore: kvStore,
	}
}

// Add adds the entry to the cache.
func (n *NATS) Add(_ context.Context, k Key, e *Entry, ttl time.Duration) error {
	key := fmt.Sprint(k)
	if key == "" {
		return nil
	}

	buf, err := e.MarshalBinary()
	if err != nil {
		return err
	}

	_, err = n.kvStore.Put(key, buf)
	return err
}

// Get gets an entry from the cache.
func (n *NATS) Get(ctx context.Context, k Key) (*Entry, error) {
	key := fmt.Sprint(k)
	if key == "" {
		return nil, ErrNotFound
	}

	entry, err := n.kvStore.Get(key)
	if err != nil {
		return nil, err
	}

	e := &Entry{}
	if err := e.UnmarshalBinary(entry.Value()); err != nil {
		return nil, err
	}

	return e, nil
}

// Del deletes an entry from the cache.
func (n *NATS) Del(_ context.Context, k Key) error {
	key := fmt.Sprint(k)
	if key == "" {
		return nil
	}

	return n.kvStore.Delete(key)
}
```
